### [Herbert Irving Comprehensive Cancer Center, Columbia University](https://cancer.columbia.edu/) (COLU)

Columbia University Irving Medical Center uses the Illumina TruSeq Amplicon --Cancer Panel (TSACP) to detect known cancer hotspots.DNA is extracted from unstained sections of FFPE tissue paired with an H&E stained section that is used to ensure adequate tumor cellularity (human assessment \> 30%) and marking of the tumor region of interest (macrodissection). Extraction for FFPE tissue is performed on the QiaCube instrument (Qiagen). 50-250ng of genomic DNA is used as input.Tumors are sequenced to an average depth of at least 1000X. Alignment (to hg19) and variant calling is performed using NextGENe v2.4.2software. Variants lower than 1% allele frequency in all three control populations (White, African American, Asian) of the Exome Variant Server database, the 1000 genome project database are retained, and annotation of variants is performed using a custom pipeline. All cases are reviewed and interpreted by a molecular pathologist.
