### [Swedish Cancer Institute](https://www.swedish.org/services/cancer-institute) (SCI)

SCI uses CellNetixPMP gene panel to detect hotspot mutations in known cancer genes from solid tumor DNA (Formalin-fixed, paraffin-embedded tissue). The hotspot gene panel covers 68 genes. Tumor cell content is greater than 10% verified by pathologist. Tumor DNA is sequenced to \>200x on average (Variant that allele frequency is less than 10% requires more than 400X) on Illumina MiSeq (TruSeq Amplicon) platform, and data is analyzed in MiSeq Reporter 2.5. Reads are aligned to hg19 reference genome by the BWA (v0.6.1-r104-tpx) aligner adapted by the MiSeq Reporter Software (v2.4.1 or v2.5) using the manufacture suggested settings. MiSeq Reporter provided Somatic Variant Caller (v2.1.12) is run on the aligned .bam files to identify variants present in DNA samples. Detailed stepsplease refer toIllumina MiSeq Reporter User Guide. Variants are filtered for allele frequency greater than 3% except for actionable mutations. Variants that are observed in $\ge$ 75% samples on the same run, or common variant with population frequency of \> 50%, or average population frequency \>5% reported in the 1000 genome and/or in ExAc. are filtered.
