### [Wake Forest University Health Sciences, Wake Forest Baptist Medical Center](https://www.wakehealth.edu/) (WAKE)

We utilized thesequencing analysis pipelines from Foundation Medicine and Caristo analyze clinical samples and support.Enrichment of target sequences was achieved by solution-based hybrid capture with custom biotinylated oligonucleotide bases. Enriched libraries were sequenced to an average median depth of \>500× with 99% of bases covered \>100× (IlluminaHiSeq2000 platform using 49 × 49 paired-end reads).The clinical sequencing data were analyzed by Foundation Medicine and Carisdevelopedpipelines.Sequenced readswere mapped to the reference human genome (hg19) using the Burrows-Wheeler Aligner and the publicly available SAM tools, Picard, and Genome Analysis Toolkit. Point mutations were identified by a Bayesian algorithm; short insertions and deletions determined by local assembly; gene copy numberalterations identified by comparison to process-matched normal controls; and gene fusions/rearrangements determined by clustering chimeric reads mapped to targeted introns.Following by computational analysis with tools such asMutSigand CHASM, the driver mutations can be identified which may help the selection of treatment strategy. In addition, the initial report of the analysis of 470 cases has been published and highlightedon the cover of the journalTheranosticsin 2017.
